name: CI
on:
  push:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.17
      - name: Test
        run: go test -v
        working-directory: test
      - name: Build
        run: bash build.sh
